# Generated by Django 5.0.4 on 2024-05-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_doctor_user_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
