# Generated by Django 5.0.4 on 2024-05-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_doctor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
