# Generated by Django 5.0.4 on 2024-05-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
