# Generated by Django 5.0.4 on 2024-05-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_remove_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
