# Generated by Django 5.0.4 on 2024-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_remove_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_datetime',
            field=models.TextField(default='[]'),
        ),
    ]
