# Generated by Django 5.0.4 on 2024-05-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_doctor_available_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='avaible_datetime',
            field=models.CharField(choices=[('Lun 01-05-2024/10:00', 'Lun 01-05-2024/10:00'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Scheduled', max_length=20),
        ),
    ]
