# Generated by Django 5.0.4 on 2024-05-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_appointment_avaible_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='avaible_datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='available_datetime',
            field=models.CharField(choices=[('Lun 01-05-2024/10:00', 'Lun 01-05-2024/10:00'), ('Lun 01-05-2024/10:00', 'Lun 01-05-2024/10:00')], default='Scheduled', max_length=20),
        ),
    ]
